name: Build
on:
  push:
    branches:
      - trunk
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v23
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: zigpkgs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: bash ci/build_all.sh
